// <auto-generated />
using EFComSQLITETeste;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFComSQLITETeste.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20190120132821_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("EFComSQLITETeste.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Telefone");

                    b.Property<int>("VisitanteId");

                    b.HasKey("Id");

                    b.HasIndex("VisitanteId")
                        .IsUnique();

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("EFComSQLITETeste.Visitante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Visitantes");
                });

            modelBuilder.Entity("EFComSQLITETeste.Contato", b =>
                {
                    b.HasOne("EFComSQLITETeste.Visitante")
                        .WithOne("Contato")
                        .HasForeignKey("EFComSQLITETeste.Contato", "VisitanteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
